### ISSUE TITLE
defense doesn't work

### ISSUE THREAD

**Issue by qiaojy19** [git-disl/DataPoisoning_FL#1]
Hi, I have some problems when I use `python3 defense.py`.

I have modified the defense.py here:

```
MODELS_PATH = "/home/xxx/DataPoisoning_FL/default_models"
EXP_INFO_PATH = "/home/xxx/DataPoisoning_FL/logs/3002.log"
```

But the program runs with error:

```
Traceback (most recent call last):
  File "defense.py", line 32, in <module>
    POISONED_WORKER_IDS = get_poisoned_worker_ids_from_log(EXP_INFO_PATH)
  File "/home/tianjc/DataPoisoning_FL/federated_learning/utils/log_file_utils.py", line 9, in get_poisoned_worker_ids_from_log
    workers = file_lines[3].split("[")[1].split("]")[0]
IndexError: list index out of range
```

In order to debug, I also modify the file `log_file_utils.py` here:

```
    with open(log_path, "r") as f:
        file_lines = [line.strip() for line in f.readlines()]
    for i in range(10):
        print('line:',i,file_lines[i])
    workers = file_lines[3].split("[")[1].split("]")[0]
```

Then I run defense.py, the result is:

```
line: 0 2020-12-02 23:43:23.080 | DEBUG    | federated_learning.arguments:log:182 - Arguments:
line: 1 Batch Size: 10
line: 2 Test Batch Size: 1000
line: 3 Epochs: 10
line: 4 Learning Rate: 0.01
line: 5 Momentum: 0.5
line: 6 CUDA Enabled: True
line: 7 Shuffle Enabled: False
line: 8 Log Interval: 100
line: 9 Scheduler Step Size: 50
Traceback (most recent call last):
  File "defense.py", line 32, in <module>
    POISONED_WORKER_IDS = get_poisoned_worker_ids_from_log(EXP_INFO_PATH)
  File "/home/xxx/DataPoisoning_FL/federated_learning/utils/log_file_utils.py", line 10, in get_poisoned_worker_ids_from_log
    workers = file_lines[3].split("[")[1].split("]")[0]
IndexError: list index out of range
```

I wish you can help me, thank you so much.

**Comment by Tang-Haojin** [comment]
Hopefully it's not too late!
You should modify some of the codes:

0. label_flipping_attack.py:13: maybe you want to personalize the number of poisoned workers
1. federated/arguments.py:36: change it to `self.save_model = True`
2. server.py:86: change it to `# args.log()`
3. defense.py:17: change it to `MODELS_PATH = "3000_models"`
4. defense.py:18: change it to `EXP_INFO_PATH = "logs/3000.log"`
5. defense.py:21: change it to `EPOCHS = list(range(1, 11))`
6. defense.py:26: change it to `LAYER_NAME = "fc.weight"` for default situation
7. delete all files in logs/
8. relaunch `python label_flipping_attack.py`
9. relaunch `python defense.py`

This works for me. Hopefully it works out for you too :)

**Comment by ChangWenhan** [comment]
OK, I know how to solve it. Just change the source class to what you choose in 'label_flipping.py'.
For example, if I choose 'replace_1_with_3':

1.defense.py:29: change it to `CLASS_NUM = 1`

This works for me. And the result looks great.
![测试](https://user-images.githubusercontent.com/53159178/115856883-9b57c100-a45f-11eb-8844-37a77fe6ee46.jpg)

**Comment by AriesQa** [comment]
here, Malicious participants are not visible with mentioned settings.  How to get output as in paper?

![defense_results](https://user-images.githubusercontent.com/85681572/121517261-95ff0780-ca08-11eb-8caa-896abf254db9.jpg)

**Comment by AriesQa** [comment]
here, Malicious participants are not visible with mentioned settings.  How to get output as in paper?

![defense_results](https://user-images.githubusercontent.com/85681572/121517521-ea09ec00-ca08-11eb-9863-fe653b9beaa8.jpg)

**Comment by DarkmatterVale** [comment]
Hi all, apologies for the late response.

As you all determined, ensuring your configuration settings are correct is critical in order to achieve reproducible results.

I'm aware of the bug in the code and will submit a PR for a fix in the near future.

**Comment by DarkmatterVale** [comment]
Bug fix pushed: https://github.com/git-disl/DataPoisoning_FL/pull/4

You will need to manually pull out the poisoned worker IDs, but the program should no longer crash.

**Comment by deepak182** [comment]
![image](https://user-images.githubusercontent.com/58266533/165655597-1b7e6241-c8cb-439b-ba28-20326a8535e1.png)
I am not getting the result as given in paper. How can i get result as in paper?
