### ISSUE TITLE
Defence Results are not like in the paper

### ISSUE THREAD

**Issue by EdaErdol** [git-disl/DataPoisoning_FL#2]
Hello,
I ran your code with the changes at [issue 1](https://github.com/git-disl/DataPoisoning_FL/issues/1). However, the results of defense.py is not like in the papers. Poisoned workers are not clustered such as in the paper. Instead of clustering their PCA results scatter accross the graph. For example I tried with only 2 poisoned workers, but here is the defense result. Is there anything else I am missing? I ran the native code with the changes at [issue 1](https://github.com/git-disl/DataPoisoning_FL/issues/1). I hope to hearing from you soon. Thank you for sharing your work.
![defense_results](https://user-images.githubusercontent.com/76816751/117857369-9af35e80-b284-11eb-830b-34f4cc211d3d.jpg)

Best regards.

**Comment by EdaErdol** [comment]
When I change the class num variable it did the trick.

**Comment by AriesQa** [comment]
> When I change the class num variable it did the trick.

It did not work for me, I have run with  defense.py:29: change it to CLASS_NUM = 1
I have tried it for 10 poisoned workers

![defense_results](https://user-images.githubusercontent.com/85681572/122636370-5fa94280-d102-11eb-9e69-f1aca75b7da1.jpg)
Thanks and looking forward to hearing from you.

**Comment by zjujy** [comment]
> > When I change the class num variable it did the trick.
> 
> It did not work for me, I have run with defense.py:29: change it to CLASS_NUM = 1 I have tried it for 10 poisoned workers
> 
> ![defense_results](https://user-images.githubusercontent.com/85681572/122636370-5fa94280-d102-11eb-9e69-f1aca75b7da1.jpg) Thanks and looking forward to hearing from you.

I have the same problem, did you solved the problem afterwards? 
Best regards.
