### ISSUE TITLE
denfense.py doesn't work

### ISSUE THREAD

**Issue by zk375142817** [git-disl/DataPoisoning_FL#6]
Hi,I'm in some trouble，Can you help me, please
All my parameters are set by default, but the following problems occur in "denfense. py":
Traceback (most recent call last):
  File "defense.py", line 76, in <module>
    start_model_files = get_model_files_for_epoch(model_files, epoch)
  File "/content/drive/MyDrive/DataPoisoning_FL-master/federated_learning/utils/model_list_parser.py", line 42, in get_model_files_for_epoch
    model_epoch_num = get_epoch_num_from_model_file_name(model)
  File "/content/drive/MyDrive/DataPoisoning_FL-master/federated_learning/utils/model_list_parser.py", line 11, in get_epoch_num_from_model_file_name
    return int(model_file_name.split("_")[2].split(".")[0])
IndexError: list index out of range
My configuration is as follows:
MODELS_PATH = "DataPoisoning_FL-master/models/3000_models
EXP_INFO_PATH = "DataPoisoning_FL-master/logs/3000.log"
EPOCHS = list(range(10,200))
CLASS_NUM = 1

**Comment by nsmalotaibi** [comment]
@zk375142817 Hi have you managed to solve this issue?? please

**Comment by zk375142817** [comment]
Yes, I have solved this issue. The cause of this problem may be that the model was not trained for 200 epochs during the training process, which resulted in the error 'list out of range'. The solution is to modify 'EPOCHS = list(range(1,10))' or to re-run the model training process and ensure that the model is fully trained.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "git-disl/DataPoisoning_FL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [git-disl/DataPoisoning_FL] denfense.py doesn't work (Issue #6)





 
@zk375142817 Hi have you managed to solve this issue?? please
